In [290]:
import os 
import pandas as pd
import numpy as np
import datetime as dt
import qgrid

In [281]:
path = str(r'C:\Users\tranchinake\Desktop\DataScienceUniversity\LabBusinessAnalytic\Psicology\DS_LAB_PSYCOLOGY_2021')
path = path.replace("\\","/")
os.chdir(path)

In [283]:
df = pd.read_csv("./dataset/dataset_europa_inghilterra_08042021/all_astrazeneca_eu_in_eu_gb_10042021.csv")
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'id', 'permalink',
       'username', 'text', 'date', 'parola_cercata', 'location', 'area',
       'citta', 'raggio', 'scores', 'compound'],
      dtype='object')

In [284]:
df = pd.read_csv("./dataset/dataset_europa_inghilterra/all_astrazeneca_eu_in_eu_gb-vader.csv")
df.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'id', 'permalink',
       'username', 'text', 'date', 'parola_cercata', 'location', 'area',
       'citta', 'raggio', 'scores', 'compound'],
      dtype='object')

In [285]:
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,id,permalink,username,text,date,parola_cercata,location,area,citta,raggio,scores,compound
0,0,0,0,1377046670383312901,https://twitter.com/CarrieAtFFCa/status/137704...,CarrieAtFFCa,AstraZeneca Changes Names Continues Use Vaccin...,2021-03-30,AstraZeneca,EU-Nord,EU,Amburg,200km,"{'neg': 0.141, 'neu': 0.859, 'pos': 0.0, 'comp...",-0.4215
1,1,1,1,1377044675564027904,https://twitter.com/LibertyTreeWND/status/1377...,LibertyTreeWND,DONT GET THE JABGermany has temporarily halted...,2021-03-30,AstraZeneca,EU-Nord,EU,Amburg,200km,"{'neg': 0.084, 'neu': 0.916, 'pos': 0.0, 'comp...",-0.4767
2,2,2,2,1377036854608953345,https://twitter.com/CatsProcurement/status/137...,CatsProcurement,US Army buys 100000 doses of AstraZeneca antib...,2021-03-30,AstraZeneca,EU-Nord,EU,Amburg,200km,"{'neg': 0.0, 'neu': 0.808, 'pos': 0.192, 'comp...",0.4215
3,3,3,3,1377036163828097028,https://twitter.com/starsandstripes/status/137...,starsandstripes,Several health authorities in Germany announce...,2021-03-30,AstraZeneca,EU-Nord,EU,Amburg,200km,"{'neg': 0.0, 'neu': 0.94, 'pos': 0.06, 'compou...",0.3182
4,4,4,4,1377029433748557831,https://twitter.com/AJBlackston/status/1377029...,AJBlackston,The Latest Germany restricts use of AstraZenec...,2021-03-30,AstraZeneca,EU-Nord,EU,Amburg,200km,"{'neg': 0.183, 'neu': 0.635, 'pos': 0.183, 'co...",0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203298,203298,28,28,1370347989567422465,https://twitter.com/Adriel_Kasonta/status/1370...,Adriel_Kasonta,UK of goods to the plunged by 407 in January d...,2021-03-12,EU,EU-est,EU,varsavia,300km,"{'neg': 0.04, 'neu': 0.96, 'pos': 0.0, 'compou...",-0.0772
203299,203299,29,29,1370061570018054155,https://twitter.com/pidybi/status/137006157001...,pidybi,EU drug regulator investigating 30 reports of ...,2021-03-11,EU,EU-est,EU,varsavia,300km,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
203300,203300,30,30,1369767203374006273,https://twitter.com/kachno85/status/1369767203...,kachno85,I am a gay and EU is my home,2021-03-10,EU,EU-est,EU,varsavia,300km,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000
203301,203301,31,31,1369346107692757004,https://twitter.com/kachno85/status/1369346107...,kachno85,I support EN resolution to declare the entire ...,2021-03-09,EU,EU-est,EU,varsavia,300km,"{'neg': 0.026, 'neu': 0.769, 'pos': 0.205, 'co...",0.8271
203302,203302,32,32,1368179324508069894,https://twitter.com/pidybi/status/136817932450...,pidybi,EU to seek AstraZeneca doses from US amid19 va...,2021-03-06,EU,EU-est,EU,varsavia,300km,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000

In [209]:
qgrid.show_grid(df,grid_options = {'forceFitColumns':False,'syncColumnCellResize': False,'highlightSelectedCell': True,'rowHeight': 25},
                show_toolbar=True,
               column_options ={ 'resizable': True,})

QgridWidget(grid_options={'fullWidthRows': True, 'syncColumnCellResize': False, 'forceFitColumns': False, 'def…

In [265]:
# df = df.drop(['Unnamed: 0.1','Unnamed: 0','Unnamed: 0.1.1','id'], axis=1)
df = df.drop(['id'], axis=1)

In [84]:
# ['date','area']
# df.groupby(['area','date'])['compound'].mean()

In [266]:
d_mean = df.groupby(['area','parola_cercata','date'],as_index=False).mean() 
d_mean
#.agg(['mean', 'median'])
# d2 = df.groupby(['date','area'],as_index=False).median()

    area parola_cercata        date  compound
0     EU    AstraZeneca  2021-03-01  0.111215
1     EU    AstraZeneca  2021-03-02  0.071454
2     EU    AstraZeneca  2021-03-03  0.044278
3     EU    AstraZeneca  2021-03-04 -0.052776
4     EU    AstraZeneca  2021-03-05  0.012180
..   ...            ...         ...       ...
103   GB             EU  2021-03-26 -0.112567
104   GB             EU  2021-03-27 -0.002525
105   GB             EU  2021-03-28  0.252300
106   GB             EU  2021-03-29 -0.142500
107   GB             EU  2021-03-30 -0.548250

[108 rows x 4 columns]

In [267]:
d_median = df.groupby(['area','parola_cercata','date'],as_index=False).median()

In [268]:
d_join = d_median.join(d_mean, lsuffix='', rsuffix='_other')
d_join

,area,parola_cercata,date,compound,area_other,parola_cercata_other,date_other,compound_other
0,EU,AstraZeneca,2021-03-01,0.00000,EU,AstraZeneca,2021-03-01,0.111215
1,EU,AstraZeneca,2021-03-02,0.00000,EU,AstraZeneca,2021-03-02,0.071454
2,EU,AstraZeneca,2021-03-03,0.00000,EU,AstraZeneca,2021-03-03,0.044278
3,EU,AstraZeneca,2021-03-04,0.00000,EU,AstraZeneca,2021-03-04,-0.052776
4,EU,AstraZeneca,2021-03-05,0.00000,EU,AstraZeneca,2021-03-05,0.012180
...,...,...,...,...,...,...,...,...
103,GB,EU,2021-03-26,-0.12660,GB,EU,2021-03-26,-0.112567
104,GB,EU,2021-03-27,0.22850,GB,EU,2021-03-27,-0.002525
105,GB,EU,2021-03-28,0.25230,GB,EU,2021-03-28,0.252300
106,GB,EU,2021-03-29,0.00000,GB,EU,2021-03-29,-0.142500
107,GB,EU,2021-03-30,-0.54825,GB,EU,2021-03-30,-0.548250

In [269]:
d_join = d_join.drop(['area_other','parola_cercata_other','date_other'], axis=1)

In [270]:
d_join = d_join.rename(columns={'compound': 'media', 'compound_other': 'median'})
d_join

    area parola_cercata        date    media    median
0     EU    AstraZeneca  2021-03-01  0.00000  0.111215
1     EU    AstraZeneca  2021-03-02  0.00000  0.071454
2     EU    AstraZeneca  2021-03-03  0.00000  0.044278
3     EU    AstraZeneca  2021-03-04  0.00000 -0.052776
4     EU    AstraZeneca  2021-03-05  0.00000  0.012180
..   ...            ...         ...      ...       ...
103   GB             EU  2021-03-26 -0.12660 -0.112567
104   GB             EU  2021-03-27  0.22850 -0.002525
105   GB             EU  2021-03-28  0.25230  0.252300
106   GB             EU  2021-03-29  0.00000 -0.142500
107   GB             EU  2021-03-30 -0.54825 -0.548250

[108 rows x 5 columns]

In [271]:
d_count = df.groupby(['area','parola_cercata','date'],as_index=False).count()
d_count = d_count.loc[:,['text','area']]
d_count

     text area
0    2654   EU
1    3937   EU
2    3322   EU
3    4789   EU
4    4051   EU
..    ...  ...
103     6   GB
104     4   GB
105     2   GB
106     5   GB
107     2   GB

[108 rows x 2 columns]

In [272]:
d_join2 = d_join.join(d_count, lsuffix='', rsuffix='_other')
d_join2

    area parola_cercata        date    media    median  text area_other
0     EU    AstraZeneca  2021-03-01  0.00000  0.111215  2654         EU
1     EU    AstraZeneca  2021-03-02  0.00000  0.071454  3937         EU
2     EU    AstraZeneca  2021-03-03  0.00000  0.044278  3322         EU
3     EU    AstraZeneca  2021-03-04  0.00000 -0.052776  4789         EU
4     EU    AstraZeneca  2021-03-05  0.00000  0.012180  4051         EU
..   ...            ...         ...      ...       ...   ...        ...
103   GB             EU  2021-03-26 -0.12660 -0.112567     6         GB
104   GB             EU  2021-03-27  0.22850 -0.002525     4         GB
105   GB             EU  2021-03-28  0.25230  0.252300     2         GB
106   GB             EU  2021-03-29  0.00000 -0.142500     5         GB
107   GB             EU  2021-03-30 -0.54825 -0.548250     2         GB

[108 rows x 7 columns]

In [275]:
d_join2 = d_join2.drop(['area_other'], axis=1)
d_join2 = d_join2.rename(columns={'text': 'count'})
d_join2

KeyError: "['area_other'] not found in axis"

In [277]:
d_join2

    area parola_cercata        date    media    median  count
0     EU    AstraZeneca  2021-03-01  0.00000  0.111215   2654
1     EU    AstraZeneca  2021-03-02  0.00000  0.071454   3937
2     EU    AstraZeneca  2021-03-03  0.00000  0.044278   3322
3     EU    AstraZeneca  2021-03-04  0.00000 -0.052776   4789
4     EU    AstraZeneca  2021-03-05  0.00000  0.012180   4051
..   ...            ...         ...      ...       ...    ...
103   GB             EU  2021-03-26 -0.12660 -0.112567      6
104   GB             EU  2021-03-27  0.22850 -0.002525      4
105   GB             EU  2021-03-28  0.25230  0.252300      2
106   GB             EU  2021-03-29  0.00000 -0.142500      5
107   GB             EU  2021-03-30 -0.54825 -0.548250      2

[108 rows x 6 columns]

In [276]:
qgrid.show_grid(d_join2,grid_options = {'forceFitColumns':False,'syncColumnCellResize': False,'highlightSelectedCell': True,'rowHeight': 25},
                show_toolbar=True,
               column_options ={ 'resizable': True,})

QgridWidget(grid_options={'fullWidthRows': True, 'syncColumnCellResize': False, 'forceFitColumns': False, 'def…

# Aggiunta righe mancanti

In [145]:
def aggiungeRigheDataMancanti(df,area,tag):
    idx = pd.date_range('03-01-2021', '03-31-2021')
    df.loc[:,'date'] = pd.to_datetime(df.loc[:,'date'])
    df = df.set_index(df.loc[:,'date'])

    df = df.reindex(idx, fill_value=0)

    df.loc[:,'area']=area
    df.loc[:,'parola_cercata']=tag
    df['date'] = df.index
    df.reset_index(level=0, inplace=True)
    df = df.drop(['index'], axis=1)
    df
    return df

In [286]:
d_Astrazeneca_EU = d_join2[(d_join2['parola_cercata']  =='AstraZeneca') & (d_join2['area']  =='EU')]

area='EU'
tag = 'AstraZeneca'
d_Astrazeneca_EU = aggiungeRigheDataMancanti(d_Astrazeneca_EU,area,tag)
d_Astrazeneca_EU

####
d_EU_EU = d_join2[(d_join2['parola_cercata']  =='EU') & (d_join2['area']  =='EU')]

area='EU'
tag = 'EU'
d_EU_EU = aggiungeRigheDataMancanti(d_EU_EU,area,tag)
d_EU_EU

####
d_EU_GB = d_join2[(d_join2['parola_cercata']  =='EU') & (d_join2['area']  =='GB')]

area='GB'
tag = 'EU'
d_EU_GB = aggiungeRigheDataMancanti(d_EU_GB,area,tag)
#d_Astrazeneca_GB


####
d_Astrazeneca_GB = d_join2[(d_join2['parola_cercata']  =='AstraZeneca') & (d_join2['area']  =='GB')]

area='GB'
tag = 'AstraZeneca'
d_Astrazeneca_GB = aggiungeRigheDataMancanti(d_Astrazeneca_GB,area,tag)
d_Astrazeneca_GB

C:\Users\tranchinake\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py:1675: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

   area parola_cercata       date    media    median  count
0    GB    AstraZeneca 2021-03-01  0.36120  0.361200      1
1    GB    AstraZeneca 2021-03-02  0.31875  0.318750      2
2    GB    AstraZeneca 2021-03-03  0.02580  0.025800      1
3    GB    AstraZeneca 2021-03-04  0.00000  0.000000      0
4    GB    AstraZeneca 2021-03-05  0.38610  0.386100      2
5    GB    AstraZeneca 2021-03-06  0.00000  0.000000      0
6    GB    AstraZeneca 2021-03-07  0.00000  0.000000      0
7    GB    AstraZeneca 2021-03-08  0.83600  0.836000      1
8    GB    AstraZeneca 2021-03-09  0.00000  0.000000      0
9    GB    AstraZeneca 2021-03-10  0.00000  0.000000      0
10   GB    AstraZeneca 2021-03-11  0.00000  0.000000      0
11   GB    AstraZeneca 2021-03-12  0.00000  0.000000      0
12   GB    AstraZeneca 2021-03-13  0.00000  0.000000      0
13   GB    AstraZeneca 2021-03-14  0.00000  0.000000      0
14   GB    AstraZeneca 2021-03-15  0.22360  0.223600      2
15   GB    AstraZeneca 2021-03-16  0.34735  0.271775      4
16   GB    AstraZeneca 2021-03-17 -0.55740 -0.557400      1
17   GB    AstraZeneca 2021-03-18  0.00000  0.000000      1
18   GB    AstraZeneca 2021-03-19  0.00000  0.041767      3
19   GB    AstraZeneca 2021-03-20  0.22020  0.220200      2
20   GB    AstraZeneca 2021-03-21 -0.38075 -0.380750      2
21   GB    AstraZeneca 2021-03-22  0.10270 -0.114786      7
22   GB    AstraZeneca 2021-03-23  0.65160  0.651600      2
23   GB    AstraZeneca 2021-03-24 -0.31820 -0.050700      3
24   GB    AstraZeneca 2021-03-25  0.29600  0.167760      5
25   GB    AstraZeneca 2021-03-26  0.58590  0.345400      3
26   GB    AstraZeneca 2021-03-27  0.00000  0.000000      3
27   GB    AstraZeneca 2021-03-28  0.65245  0.652450      2
28   GB    AstraZeneca 2021-03-29  0.94850  0.948500      1
29   GB    AstraZeneca 2021-03-30  0.00000  0.000000      0
30   GB    AstraZeneca 2021-03-31  0.00000  0.000000      0

# Coefficiente di Correlazione

R^2

In [303]:
x_values = d_Astrazeneca_GB['median']
y_values = d_Astrazeneca_EU['median']


correlation_matrix = np.corrcoef(x_values, y_values)
correlation_xy = correlation_matrix[0,1]
r_squared = correlation_xy**2

print(r_squared)
# correlation_matrix

0.015563155252308059

In [236]:
dfAll = pd.DataFrame()
# 27 stati
list = ["Austria", "Belgium", "Bulgaria", "Norway","Croatia", "Republic of Cyprus", "Czech Republic", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg", "Malta", "Netherlands", "Poland", "Portugal", "Romania", "Slovakia", "Slovenia", "Spain", "Sweden"]
# list_uk = ["England", "Northern Ireland","Scotland","Wales"]
list_uk = ["United Kingdom"]



for stato in list:
    d_Astrazeneca_EU['stato'] = stato
    dfAll = dfAll.append(d_Astrazeneca_EU)
d_Astrazeneca_EU_all = dfAll

dfAll = pd.DataFrame()
for stato in list_uk:
    d_Astrazeneca_GB['stato'] = stato
    dfAll = dfAll.append(d_Astrazeneca_GB)
d_Astrazeneca_GB_all = dfAll

dfAll = pd.DataFrame()
for stato in list:
    d_EU_EU['stato'] = stato
    dfAll = dfAll.append(d_EU_EU)
d_EU_EU_all = dfAll

dfAll = pd.DataFrame()
for stato in list_uk:
    d_EU_GB['stato'] = stato
    dfAll = dfAll.append(d_EU_GB)
d_EU_GB = dfAll

In [183]:
d_Astrazeneca_EU_all

   area parola_cercata       date  media    median  count    stato
0    EU    AstraZeneca 2021-03-01    0.0  0.000000      0  Austria
1    EU    AstraZeneca 2021-03-02    0.0  0.000000      0  Austria
2    EU    AstraZeneca 2021-03-03    0.0  0.000000      0  Austria
3    EU    AstraZeneca 2021-03-04    0.0  0.000000      0  Austria
4    EU    AstraZeneca 2021-03-05    0.0  0.000000      1  Austria
..  ...            ...        ...    ...       ...    ...      ...
26   EU    AstraZeneca 2021-03-27    0.0  0.045078   2740   Sweden
27   EU    AstraZeneca 2021-03-28    0.0  0.037061   1806   Sweden
28   EU    AstraZeneca 2021-03-29    0.0  0.026308   5000   Sweden
29   EU    AstraZeneca 2021-03-30    0.0 -0.050216   8573   Sweden
30   EU    AstraZeneca 2021-03-31    0.0  0.000000      0   Sweden

[837 rows x 7 columns]

In [184]:
d_EU_EU_all

   area parola_cercata       date   media    median  count    stato
0    EU             EU 2021-03-01  0.0170  0.020560      5  Austria
1    EU             EU 2021-03-02  0.0000 -0.295360      5  Austria
2    EU             EU 2021-03-03  0.0000 -0.060300      9  Austria
3    EU             EU 2021-03-04  0.0000 -0.026300      8  Austria
4    EU             EU 2021-03-05  0.1798  0.354478      9  Austria
..  ...            ...        ...     ...       ...    ...      ...
26   EU             EU 2021-03-27  0.0000 -0.138645  22222   Sweden
27   EU             EU 2021-03-28  0.0000 -0.098740  17136   Sweden
28   EU             EU 2021-03-29  0.0000 -0.079405  24939   Sweden
29   EU             EU 2021-03-30  0.0000  0.013184  23882   Sweden
30   EU             EU 2021-03-31  0.0000  0.000000      0   Sweden

[837 rows x 7 columns]

In [185]:
d_EU_GB

   area parola_cercata       date    media    median  count    stato
0    GB             EU 2021-03-01  0.05695  0.007532     22  England
1    GB             EU 2021-03-02  0.29570  0.195295     22  England
2    GB             EU 2021-03-03 -0.22630 -0.166729     31  England
3    GB             EU 2021-03-04  0.00000 -0.005421     33  England
4    GB             EU 2021-03-05 -0.33890 -0.099447     34  England
..  ...            ...        ...      ...       ...    ...      ...
26   GB             EU 2021-03-27 -0.00645 -0.091037     16    Wales
27   GB             EU 2021-03-28  0.10270  0.101323     13    Wales
28   GB             EU 2021-03-29 -0.30560 -0.248875     24    Wales
29   GB             EU 2021-03-30  0.00000  0.027812    746    Wales
30   GB             EU 2021-03-31  0.00000  0.000000      0    Wales

[124 rows x 7 columns]

In [186]:
d_Astrazeneca_GB_all

   area parola_cercata       date   media    median  count    stato
0    EU    AstraZeneca 2021-03-01  0.0000  0.022367      6  England
1    EU    AstraZeneca 2021-03-02  0.0000  0.001233     12  England
2    EU    AstraZeneca 2021-03-03  0.0129  0.017000      8  England
3    EU    AstraZeneca 2021-03-04  0.0000  0.074620      5  England
4    EU    AstraZeneca 2021-03-05  0.1626  0.165140     10  England
..  ...            ...        ...     ...       ...    ...      ...
26   EU    AstraZeneca 2021-03-27  0.0000  0.274246     13    Wales
27   EU    AstraZeneca 2021-03-28  0.5574  0.349611      9    Wales
28   EU    AstraZeneca 2021-03-29  0.4404  0.273722      9    Wales
29   EU    AstraZeneca 2021-03-30  0.0000 -0.037208    407    Wales
30   EU    AstraZeneca 2021-03-31  0.0000  0.000000      0    Wales

[124 rows x 7 columns]

In [237]:
df = d_Astrazeneca_EU_all.append(d_EU_EU_all).append(d_EU_GB).append(d_Astrazeneca_GB_all)

In [238]:
df

   area parola_cercata       date   media    median  count           stato
0    EU    AstraZeneca 2021-03-01  0.0000  0.000000      0         Austria
1    EU    AstraZeneca 2021-03-02  0.0000  0.000000      0         Austria
2    EU    AstraZeneca 2021-03-03  0.0000  0.000000      0         Austria
3    EU    AstraZeneca 2021-03-04  0.0000  0.000000      0         Austria
4    EU    AstraZeneca 2021-03-05  0.0000  0.000000      1         Austria
..  ...            ...        ...     ...       ...    ...             ...
26   GB    AstraZeneca 2021-03-27  0.0000  0.274246     13  United Kingdom
27   GB    AstraZeneca 2021-03-28  0.5574  0.349611      9  United Kingdom
28   GB    AstraZeneca 2021-03-29  0.4404  0.273722      9  United Kingdom
29   GB    AstraZeneca 2021-03-30  0.0000 -0.037208    407  United Kingdom
30   GB    AstraZeneca 2021-03-31  0.0000  0.000000      0  United Kingdom

[1798 rows x 7 columns]

In [239]:
qgrid.show_grid(df,grid_options = {'forceFitColumns':False,'syncColumnCellResize': False,'highlightSelectedCell': True,'rowHeight': 25},
                show_toolbar=True,
               column_options ={ 'resizable': True,})

QgridWidget(grid_options={'fullWidthRows': True, 'syncColumnCellResize': False, 'forceFitColumns': False, 'def…

In [229]:
df[df['stato'].isna()]

Empty DataFrame
Columns: [area, parola_cercata, date, media, median, count, stato]
Index: []

In [240]:
path = './dataset/'
df.to_csv(path+"dataset_definitivo_tableau.csv",sep=';',decimal=',')